### ISSUE TITLE
Wenn zu viele Tasks da sind, sieht der Kalender schlecht aus

### ISSUE THREAD

**Issue by Jazylucky** [cooukiez/calendar#2]

**Comment by cooukiez** [comment]
zeig mal beispiel verstehe nicht ganz was du meinst

**Comment by cooukiez** [comment]
peter regelt

**Comment by Aphavalpha** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu05WMgrSOaiezsz_WsZPaGgLyINnONS5rpg&s
