### ISSUE TITLE
Im Main Branch sind die ganzen Dependencies

### ISSUE THREAD

**Issue by Jazylucky** [cooukiez/calendar#3]
**Warum Dependencies nicht im Main Branch liegen sollten**

Das Hauptziel des Main Branches in einem Versionskontrollsystem wie Git ist es, einen stabilen und funktionierenden Zustand des Projekts zu repräsentieren. Dependencies, also Abhängigkeiten von externen Bibliotheken oder Paketen, sollten nicht direkt im Main Branch verwaltet werden. Hier sind einige Gründe, warum das so ist:

**1. Reduzierung der Repository-Größe**

Dependencies können oft große Dateien und viele kleine Dateien umfassen. Wenn diese in das Repository aufgenommen werden, kann dies die Größe des Repositories erheblich vergrößern. Dies führt zu längeren Klonzeiten und erhöhtem Speicherbedarf, was die Effizienz der Entwickler beeinträchtigen kann.

**2. Klarheit und Übersichtlichkeit**

Der Main Branch sollte so klar und übersichtlich wie möglich sein, um die Verwaltung und das Verständnis des Projekts zu erleichtern. Dependencies gehören nicht zum eigentlichen Quellcode des Projekts und können daher die Übersichtlichkeit beeinträchtigen.

**3. Versionskontrolle und Konflikte**

Dependencies ändern sich häufig und können zu Versionskonflikten führen, wenn sie direkt im Main Branch verwaltet werden. Es ist besser, nur die Versionsinformationen und die Quellen der Dependencies zu verwalten (z. B. in einer requirements.txt-Datei oder einer package.json-Datei), anstatt die tatsächlichen Dateien in das Repository aufzunehmen.

**4. Wiederholbarkeit und Konsistenz**

Durch die Verwendung von Paketmanagern (wie pip für Python, npm für Node.js oder Maven für Java) können Dependencies konsistent und reproduzierbar installiert werden. Dies stellt sicher, dass alle Entwickler und Build-Umgebungen die gleichen Versionen der Dependencies verwenden, ohne dass diese im Repository gespeichert werden müssen.

**5. Einfache Aktualisierung**

Dependencies können sich schnell weiterentwickeln. Wenn sie direkt im Main Branch liegen, wird das Aktualisieren auf neue Versionen umständlich und fehleranfällig. Durch die Verwaltung der Dependencies in einer Konfigurationsdatei können sie einfacher und sicherer aktualisiert werden.

**6. Sicherheitsaspekte**

Dependencies können Sicherheitslücken enthalten. Wenn sie direkt im Main Branch liegen, kann es schwieriger sein, diese zu erkennen und zu aktualisieren. Ein Paketmanager kann helfen, Sicherheitsupdates effizienter zu verwalten und sicherzustellen, dass alle Abhängigkeiten auf dem neuesten Stand sind.

**7. Trennung von Code und Konfiguration**

Es ist eine bewährte Praxis, Code und Konfigurationsdateien zu trennen. Dependencies gehören zur Konfiguration des Projekts und sollten daher getrennt vom eigentlichen Quellcode verwaltet werden.

**Comment by Aphavalpha** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0ykHNUpQ-K_QuaafgSLTaeXpG5mHHAcFiUg&s
