### ISSUE TITLE
Hier werden alle konstruktiven Issues geblockt - eine Diktatur

### ISSUE THREAD

**Issue by Jazylucky** [cooukiez/calendar#4]
Boykottiert den Kalender!

peter ran da

**Comment by Jazylucky** [comment]
Blah

**Comment by cooukiez** [comment]
peter jetzt mach mal was

**Comment by Jazylucky** [comment]
ja echt es dauert voll lange

**Comment by Aphavalpha** [comment]
![szFxG0b3](https://github.com/user-attachments/assets/43ad8659-3422-44c6-b90d-6f2d5b649f62)
