### ISSUE TITLE
Und dann wird man auch noch mit chinesischen Männern zugespammt

### ISSUE THREAD

**Issue by Jazylucky** [cooukiez/calendar#5]

**Comment by cooukiez** [comment]
peter jetzt arbeite auch mal

**Comment by Aphavalpha** [comment]
![Uploading DALL·E 2024-10-17 21.27.15 - A traditional elderly Chinese man with a long white beard and wearing a traditional robe, giving the viewer a middle finger. The setting is outdoors w.png…]()

**Comment by Aphavalpha** [comment]
![DALL·E 2024-10-17 21 27 15 - A traditional elderly Chinese man with a long white beard and wearing a traditional robe, giving the viewer a middle finger  The setting is outdoors w](https://github.com/user-attachments/assets/3533f7fc-d212-4905-a0fe-aaf132cb495e)
