### ISSUE TITLE
Der Support ist hier sehr schlecht. Es braucht echt lange um eine Antwort zu erhalten

### ISSUE THREAD

**Issue by Jazylucky** [cooukiez/calendar#6]

**Comment by cooukiez** [comment]
peter dein job

**Comment by Aphavalpha** [comment]
![DALL·E 2024-10-17 21 30 45 - A colorful and playful cartoon character inspired by Mexican culture, with exaggerated features and a humorous expression of anger  The character has ](https://github.com/user-attachments/assets/2d14c6ea-4e5d-4d23-9ae8-3e6a7d327f6e)

**Comment by Aphavalpha** [comment]
bester Support!
